"""Initial schema

Revision ID: 012a3436efa2
Revises: 
Create Date: 2026-02-26 01:27:14.779000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012a3436efa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tzid', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_households_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_invite_code'), ['invite_code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('display_name', sa.String(length=30), nullable=True),
    sa.Column('tagline', sa.String(length=100), nullable=True),
    sa.Column('profile_img', sa.String(length=256), nullable=True),
    sa.Column('banner_img', sa.String(length=256), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('daily_checkin', sa.Boolean(), nullable=False),
    sa.Column('last_checkin', sa.DateTime(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_users_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_announcements_household_id_households')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_announcements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checkins_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins')),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_checkins_user_localdate')
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_time', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tzid', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_events_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Enum('happy', 'content', 'neutral', 'tired', 'stressed', 'sick', 'busy', 'bored', 'accomplished', 'proud', 'excited', 'productive', 'overwhelmed', 'motivated', 'cozy', 'inspired', name='mood_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_moods_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moods')),
    sa.UniqueConstraint('user_id', name='uq_user_moods_user_id')
    )
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moods_user_id'), ['user_id'], unique=True)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reminder_type', sa.Enum('CUSTOM', 'TASK_DUE', 'EVENT_STARTING', 'DAILY_CHECKIN_MISSING', name='remindertype'), nullable=False),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=True),
    sa.Column('source_entity_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reminders_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_reminders_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders')),
    sa.UniqueConstraint('household_id', 'source_entity_type', 'source_entity_id', 'trigger_at', 'reminder_type', name='uq_auto_reminder_instance')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_trigger_at'), ['trigger_at'], unique=False)

    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_shopping_lists_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_lists'))
    )
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_lists_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_shopping_lists_household_id_id', ['household_id', 'id'], unique=False)

    op.create_table('tasklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('all_members', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('icon', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('view_mode', sa.String(length=20), nullable=True),
    sa.Column('default_sort_order', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('default_filters', sa.JSON(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_by', sa.Integer(), nullable=True),
    sa.Column('show_completed', sa.Boolean(), nullable=True),
    sa.Column('new_item_position', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], name=op.f('fk_tasklists_archived_by_users')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_tasklists_creator_id_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_tasklists_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasklists'))
    )
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.create_index('ix_tasklists_creator_id', ['creator_id'], unique=False)
        batch_op.create_index('ix_tasklists_household_id', ['household_id'], unique=False)

    op.create_table('announcement_seen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('fk_announcement_seen_announcement_id_announcements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_announcement_seen_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement_seen')),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_announcement_user_seen')
    )
    op.create_table('reminder_assignments',
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], name=op.f('fk_reminder_assignments_reminder_id_reminders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminder_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id', 'user_id', name=op.f('pk_reminder_assignments'))
    )
    op.create_table('shopping_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], name=op.f('fk_shopping_categories_list_id_shopping_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_categories')),
    sa.UniqueConstraint('list_id', 'name', name='uq_category_list_id_name')
    )
    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_categories_list_id'), ['list_id'], unique=False)

    op.create_table('tasklist_members',
    sa.Column('tasklist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tasklist_id'], ['tasklists.id'], name=op.f('fk_tasklist_members_tasklist_id_tasklists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasklist_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tasklist_id', 'user_id', name=op.f('pk_tasklist_members'))
    )
    with op.batch_alter_table('tasklist_members', schema=None) as batch_op:
        batch_op.create_index('ix_tlm_user_id', ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_tasks_assigned_to_id_users')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_tasks_creator_id_users')),
    sa.ForeignKeyConstraint(['list_id'], ['tasklists.id'], name=op.f('fk_tasks_list_id_tasklists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('featured_tasklist_id', sa.Integer(), nullable=True),
    sa.Column('featured_tasklist_filter_just_me', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_filter_overdue', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_filter_due_today', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_filter_due_soon', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_important_only', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_max_items', sa.Integer(), nullable=False),
    sa.Column('featured_tasklist_show_completed', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_sort_order', sa.Enum('DUE_DATE', 'IMPORTANCE', 'MANUAL', 'NEWEST', 'OLDEST', 'ALPHABETICAL', name='featuredtasksortorder'), nullable=False),
    sa.Column('featured_tasklist_view', sa.Enum('DETAILED', 'COMPACT', name='featuredlistview'), nullable=False),
    sa.Column('featured_tasklist_show_progress', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_show_quick_add', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['featured_tasklist_id'], ['tasklists.id'], name=op.f('fk_user_settings_featured_tasklist_id_tasklists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shopping_categories.id'], name=op.f('fk_shopping_items_category_id_shopping_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], name=op.f('fk_shopping_items_list_id_shopping_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_items'))
    )
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_items_list_id'), ['list_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_items_category_id'))

    op.drop_table('shopping_items')
    op.drop_table('user_settings')
    op.drop_table('tasks')
    with op.batch_alter_table('tasklist_members', schema=None) as batch_op:
        batch_op.drop_index('ix_tlm_user_id')

    op.drop_table('tasklist_members')
    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_categories_list_id'))

    op.drop_table('shopping_categories')
    op.drop_table('reminder_assignments')
    op.drop_table('announcement_seen')
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.drop_index('ix_tasklists_household_id')
        batch_op.drop_index('ix_tasklists_creator_id')

    op.drop_table('tasklists')
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_index('ix_shopping_lists_household_id_id')
        batch_op.drop_index(batch_op.f('ix_shopping_lists_household_id'))

    op.drop_table('shopping_lists')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_trigger_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_is_active'))
        batch_op.drop_index(batch_op.f('ix_reminders_household_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_created_by_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moods_user_id'))

    op.drop_table('moods')
    op.drop_table('events')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_user_id'))

    op.drop_table('checkins')
    op.drop_table('announcements')
    op.drop_table('users')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_invite_code'))

    op.drop_table('households')
    # ### end Alembic commands ###
