"""empty message

Revision ID: 016e8b39e666
Revises: 5e40c46869c9
Create Date: 2026-02-16 14:06:25.987271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016e8b39e666'
down_revision = '5e40c46869c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_tasklist_important_only', sa.Boolean(), nullable=True))
        batch_op.drop_column('feautred_tasklist_important_only')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feautred_tasklist_important_only', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('featured_tasklist_important_only')

    # ### end Alembic commands ###
