"""empty message

Revision ID: 024e0e0e5caf
Revises: 379f8203a705
Create Date: 2026-02-17 18:39:15.791779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024e0e0e5caf'
down_revision = '379f8203a705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('featured_tasklist_rotation',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Boolean(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('featured_tasklist_rotation',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=13),
               nullable=False)

    # ### end Alembic commands ###
