"""reduce shopping list item name length to 100

Revision ID: 025f2c218ea9
Revises: 564c6f2f8f8a
Create Date: 2026-06-28 05:01:53.697267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025f2c218ea9'
down_revision = '564c6f2f8f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
