"""empty message

Revision ID: 0670a509ba1d
Revises: 74a71f793be7
Create Date: 2026-01-21 13:28:37.324642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0670a509ba1d'
down_revision = '74a71f793be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('auto_hide_when_empty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_hide_when_empty', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('show_completed')

    # ### end Alembic commands ###
