"""empty message

Revision ID: 0790f7f5e980
Revises: 3991a9ee5b40
Create Date: 2026-06-18 16:33:56.128763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0790f7f5e980'
down_revision = '3991a9ee5b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
