"""empty message

Revision ID: 0942dd1f731c
Revises: 2a8ec1c1e604
Create Date: 2025-10-10 15:26:57.324510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0942dd1f731c'
down_revision = '2a8ec1c1e604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_time', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('has_time')

    # ### end Alembic commands ###
