"""empty message

Revision ID: 09ededf82189
Revises: 025f2c218ea9
Create Date: 2026-07-01 07:37:53.299993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ededf82189'
down_revision = '025f2c218ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        op.add_column('shopping_lists', sa.Column('default_sort', sa.String(10), nullable=False, server_default='created'))
        op.add_column('shopping_lists', sa.Column('group_by_category', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_column('group_by_category')
        batch_op.drop_column('default_sort')

    # ### end Alembic commands ###
