"""empty message

Revision ID: 10ef24070015
Revises: 650113d6d4d4
Create Date: 2025-10-27 03:54:17.457196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ef24070015'
down_revision = '650113d6d4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_households_invite_code'), type_='unique')
        batch_op.create_index(batch_op.f('ix_households_invite_code'), ['invite_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_invite_code'))
        batch_op.create_unique_constraint(batch_op.f('uq_households_invite_code'), ['invite_code'])

    # ### end Alembic commands ###
