"""empty message

Revision ID: 1211806a65ac
Revises: 012a3436efa2
Create Date: 2026-03-02 00:12:00.874577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1211806a65ac'
down_revision = '012a3436efa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_date', sa.Date(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reminders_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_trigger_at'))
        batch_op.drop_constraint(batch_op.f('uq_auto_reminder_instance'), type_='unique')
        batch_op.create_unique_constraint('uq_auto_reminder_instance', ['household_id', 'source_entity_type', 'source_entity_id', 'trigger_date', 'reminder_type'])
        batch_op.create_index(batch_op.f('ix_reminders_trigger_date'), ['trigger_date'], unique=False)
        batch_op.drop_column('trigger_at')
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('trigger_at', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reminders_trigger_date'))
        batch_op.drop_constraint('uq_auto_reminder_instance', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_auto_reminder_instance'), ['household_id', 'source_entity_type', 'source_entity_id', 'trigger_at', 'reminder_type'])
        batch_op.create_index(batch_op.f('ix_reminders_trigger_at'), ['trigger_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_delivered_at'), ['delivered_at'], unique=False)
        batch_op.drop_column('trigger_date')

    # ### end Alembic commands ###
