"""empty message

Revision ID: 13f3fe03e513
Revises: 3f1b815426f0
Create Date: 2026-02-07 20:11:18.427403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f3fe03e513'
down_revision = '3f1b815426f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_expires_at'))
        batch_op.drop_constraint(batch_op.f('uq_reminder_source_entity'), type_='unique')
        batch_op.create_unique_constraint('uq_auto_reminder_instance', ['household_id', 'source_entity_type', 'source_entity_id', 'trigger_at', 'reminder_type'])
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_auto_reminder_instance', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_reminder_source_entity'), ['household_id', 'source_entity_type', 'source_entity_id'])
        batch_op.create_index(batch_op.f('ix_reminders_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###
