"""empty message

Revision ID: 209f1faa3e00
Revises: 09ededf82189
Create Date: 2026-07-01 10:50:36.712179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209f1faa3e00'
down_revision = '09ededf82189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.drop_column('archived_date')

    # ### end Alembic commands ###
