"""empty message

Revision ID: 236f4d9f9593
Revises: adfe3f864709
Create Date: 2026-03-23 12:22:12.720340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236f4d9f9593'
down_revision = 'adfe3f864709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_theme', sa.Enum('LIGHT', 'DARK', 'SYSTEM', name='theme'), nullable=False),
    sa.Column('habits_on_homepage', sa.Boolean(), nullable=False),
    sa.Column('habits_privacy_mode', sa.Enum('NORMAL', 'ALL_PRIVATE', 'PRIVATE_BY_DEFAULT', name='privacymode'), nullable=False),
    sa.Column('notes_privacy_mode', sa.Enum('NORMAL', 'ALL_PRIVATE', 'PRIVATE_BY_DEFAULT', name='privacymode'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
