"""add audience_ids to activity_events

Revision ID: 297a399c4dda
Revises: 85ca0ce638f0
Create Date: 2026-05-16 08:10:54.027155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297a399c4dda'
down_revision = '85ca0ce638f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_column('audience_ids')

    # ### end Alembic commands ###
