"""empty message

Revision ID: 2a8ec1c1e604
Revises: acee2f6b19a9
Create Date: 2025-10-03 19:58:59.309815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8ec1c1e604'
down_revision = 'acee2f6b19a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_categories_list_id'), ['list_id'], unique=False)
        batch_op.create_unique_constraint('uq_category_list_id_name', ['list_id', 'name'])
        batch_op.drop_constraint(batch_op.f('fk_shopping_categories_item_id_shopping_items'), type_='foreignkey')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopping_category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('shopping_list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('purchased',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_shopping_items_shopping_category_id'), ['shopping_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_items_shopping_list_id'), ['shopping_list_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_shopping_category_id_shopping_categories'), 'shopping_categories', ['shopping_category_id'], ['id'])

    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_lists_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_shopping_lists_household_id_id', ['household_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_index('ix_shopping_lists_household_id_id')
        batch_op.drop_index(batch_op.f('ix_shopping_lists_household_id'))

    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_shopping_category_id_shopping_categories'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shopping_items_shopping_list_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_items_shopping_category_id'))
        batch_op.alter_column('purchased',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shopping_list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('shopping_category_id')

    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shopping_categories_item_id_shopping_items'), 'shopping_items', ['item_id'], ['id'])
        batch_op.drop_constraint('uq_category_list_id_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_shopping_categories_list_id'))

    # ### end Alembic commands ###
