"""empty message

Revision ID: 2cda1106d7b7
Revises: a8c1643d28ab
Create Date: 2026-08-02 14:30:12.167418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cda1106d7b7'
down_revision = 'a8c1643d28ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('events_color')

    # ### end Alembic commands ###
