"""empty message

Revision ID: 35ec8bf714bb
Revises: 0942dd1f731c
Create Date: 2025-10-13 08:40:38.217051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ec8bf714bb'
down_revision = '0942dd1f731c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_shopping_category_id_shopping_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_shopping_category_id_shopping_categories'), 'shopping_categories', ['shopping_category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_shopping_category_id_shopping_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_shopping_category_id_shopping_categories'), 'shopping_categories', ['shopping_category_id'], ['id'])

    # ### end Alembic commands ###
