"""empty message

Revision ID: 379f8203a705
Revises: f65feee1907a
Create Date: 2026-02-17 05:29:52.488067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379f8203a705'
down_revision = 'f65feee1907a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_tasklist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_settings_featured_tasklist_id_tasklists'), 'tasklists', ['featured_tasklist_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_featured_tasklist_id_tasklists'), type_='foreignkey')
        batch_op.drop_column('featured_tasklist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_tasklist_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_featured_tasklist_id_tasklists'), 'tasklists', ['featured_tasklist_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_settings_featured_tasklist_id_tasklists'), type_='foreignkey')
        batch_op.drop_column('featured_tasklist_id')

    # ### end Alembic commands ###
