"""empty message

Revision ID: 3991a9ee5b40
Revises: ff82e98db216
Create Date: 2026-05-20 03:20:33.956510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3991a9ee5b40'
down_revision = 'ff82e98db216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
