"""empty message

Revision ID: 3b7923063ddf
Revises: af533ad7ccb1
Create Date: 2026-02-04 00:10:20.674287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7923063ddf'
down_revision = 'af533ad7ccb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reminder_type', sa.Enum('custom', 'task_due', 'event_starting', 'daily_check_in_missing', name='remindertype'), nullable=False),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=True),
    sa.Column('source_entity_type', sa.String(length=50), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_reminders_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reminders_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_reminders_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders')),
    sa.UniqueConstraint('household_id', 'source_entity_type', 'source_entity_id', name='uq_reminder_source_entity')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_trigger_at'), ['trigger_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_trigger_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_household_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_expires_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_due_at'))
        batch_op.drop_index(batch_op.f('ix_reminders_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_reminders_assigned_to_id'))

    op.drop_table('reminders')
    # ### end Alembic commands ###
