"""empty message

Revision ID: 3f1b815426f0
Revises: d3675a50b3ae
Create Date: 2026-02-07 03:57:13.150498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1b815426f0'
down_revision = 'd3675a50b3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reminders_due_at'))
        batch_op.create_index(batch_op.f('ix_reminders_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_is_active'), ['is_active'], unique=False)
        batch_op.drop_column('due_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_at', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reminders_is_active'))
        batch_op.drop_index(batch_op.f('ix_reminders_delivered_at'))
        batch_op.create_index(batch_op.f('ix_reminders_due_at'), ['due_at'], unique=False)
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
