"""empty message

Revision ID: 4053088c7a72
Revises: 4b414d2019aa
Create Date: 2026-01-17 08:18:33.484709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4053088c7a72'
down_revision = '4b414d2019aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars_at_top', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.drop_column('stars_at_top')

    # ### end Alembic commands ###
