"""empty message

Revision ID: 4541cc24a7df
Revises: 3efd3be37dc1
Create Date: 2026-03-22 12:05:21.416934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4541cc24a7df'
down_revision = '3efd3be37dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured_list_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tasklist_id', sa.Integer(), nullable=True),
    sa.Column('filter_just_me', sa.Boolean(), nullable=True),
    sa.Column('filter_overdue', sa.Boolean(), nullable=True),
    sa.Column('filter_due_today', sa.Boolean(), nullable=True),
    sa.Column('filter_due_soon', sa.Boolean(), nullable=True),
    sa.Column('important_only', sa.Boolean(), nullable=True),
    sa.Column('max_items', sa.Integer(), nullable=False),
    sa.Column('show_completed', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Enum('DUE_DATE', 'IMPORTANCE', 'MANUAL', 'NEWEST', 'OLDEST', 'ALPHABETICAL', name='featuredtasksortorder'), nullable=False),
    sa.Column('view', sa.Enum('DETAILED', 'COMPACT', name='featuredlistview'), nullable=False),
    sa.Column('show_progress', sa.Boolean(), nullable=True),
    sa.Column('show_quick_add', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tasklist_id'], ['tasklists.id'], name=op.f('fk_featured_list_settings_tasklist_id_tasklists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_featured_list_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_featured_list_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_featured_list_settings_user_id'))
    )
    op.drop_table('user_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('featured_tasklist_id', sa.INTEGER(), nullable=True),
    sa.Column('featured_tasklist_filter_just_me', sa.BOOLEAN(), nullable=True),
    sa.Column('featured_tasklist_filter_overdue', sa.BOOLEAN(), nullable=True),
    sa.Column('featured_tasklist_filter_due_today', sa.BOOLEAN(), nullable=True),
    sa.Column('featured_tasklist_filter_due_soon', sa.BOOLEAN(), nullable=True),
    sa.Column('featured_tasklist_important_only', sa.BOOLEAN(), nullable=True),
    sa.Column('featured_tasklist_max_items', sa.INTEGER(), nullable=False),
    sa.Column('featured_tasklist_show_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('featured_tasklist_sort_order', sa.VARCHAR(length=12), nullable=False),
    sa.Column('featured_tasklist_view', sa.VARCHAR(length=8), nullable=False),
    sa.Column('featured_tasklist_show_progress', sa.BOOLEAN(), nullable=True),
    sa.Column('featured_tasklist_show_quick_add', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['featured_tasklist_id'], ['tasklists.id'], name=op.f('fk_user_settings_featured_tasklist_id_tasklists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.drop_table('featured_list_settings')
    # ### end Alembic commands ###
