"""empty message

Revision ID: 4b414d2019aa
Revises: 7c87f9039c34
Create Date: 2026-01-15 14:37:22.955724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4b414d2019aa'
down_revision = '7c87f9039c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.alter_column('default_filters',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.alter_column('default_filters',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
