"""empty message

Revision ID: 51ee42474511
Revises: be533a82f4d5
Create Date: 2025-10-03 19:06:22.412827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ee42474511'
down_revision = 'be533a82f4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shopping_lists_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shopping_lists_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
