"""empty message

Revision ID: 564c6f2f8f8a
Revises: 0790f7f5e980
Create Date: 2026-06-21 02:35:33.269665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c6f2f8f8a'
down_revision = '0790f7f5e980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_item_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_item_units_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_item_units')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_unit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_item_units')
    # ### end Alembic commands ###
