"""add source_entity_metadata to reminders

Revision ID: 5b711dcfd158
Revises: fd1d41cab37e
Create Date: 2026-03-13 01:27:23.220501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b711dcfd158'
down_revision = 'fd1d41cab37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_entity_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_column('source_entity_metadata')

    # ### end Alembic commands ###
