"""empty message

Revision ID: 5e40c46869c9
Revises: 2990def889d7
Create Date: 2026-02-16 06:34:53.442886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e40c46869c9'
down_revision = '2990def889d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('featured_tasklist_rotation', sa.Enum('MANUAL', 'AUTO_ROTATE', 'MOST_DUE_SOON', name='featuredtasklistrotation'), nullable=False),
    sa.Column('featured_tasklist_assignee_filter', sa.Enum('JUST_ME', 'ALL_TASKS', name='taskassigneefilter'), nullable=False),
    sa.Column('featured_tasklist_urgency_filter', sa.Enum('ALL', 'OVERDUE_ONLY', 'DUE_TODAY', 'DUE_THIS_WEEK', name='taskurgencyfilter'), nullable=False),
    sa.Column('feautred_tasklist_important_only', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_max_items', sa.Integer(), nullable=False),
    sa.Column('featured_tasklist_show_completed', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_sort_order', sa.Enum('DUE_DATE', 'IMPORTANCE', 'MANUAL', 'NEWEST', 'OLDEST', 'ALPHABETICAL', name='featuredtasksortorder'), nullable=False),
    sa.Column('featured_tasklist_view', sa.Enum('DETAILED', 'COMPACT', name='featuredlistview'), nullable=False),
    sa.Column('featured_tasklist_show_progress', sa.Boolean(), nullable=True),
    sa.Column('featured_tasklist_show_quick_add', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
