"""empty message

Revision ID: 650113d6d4d4
Revises: e4c9b4eb9f15
Create Date: 2025-10-18 03:46:32.509286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650113d6d4d4'
down_revision = 'e4c9b4eb9f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tzid', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('announcements_ttl_mode', sa.Enum('rolling', 'midnight', name='ann_ttl_mode'), server_default='rolling', nullable=False))
        batch_op.add_column(sa.Column('announcements_ttl_hours', sa.Integer(), server_default='24', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_column('announcements_ttl_hours')
        batch_op.drop_column('announcements_ttl_mode')
        batch_op.drop_column('tzid')

    # ### end Alembic commands ###
