"""empty message

Revision ID: 74a71f793be7
Revises: 4053088c7a72
Create Date: 2026-01-17 22:06:43.623315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a71f793be7'
down_revision = '4053088c7a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.alter_column('stars_at_top',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.alter_column('stars_at_top',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
