"""empty message

Revision ID: 781ba5252c16
Revises: b453830e382d
Create Date: 2026-01-10 18:13:51.219619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781ba5252c16'
down_revision = 'b453830e382d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), nullable=True))
        batch_op.drop_column('priority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.TEXT(), nullable=True))
        batch_op.drop_column('is_important')

    # ### end Alembic commands ###
