"""empty message

Revision ID: 7b306fb886fc
Revises: 781ba5252c16
Create Date: 2026-01-10 22:39:15.035866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b306fb886fc'
down_revision = '781ba5252c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_creator_id_users'), 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_creator_id_users'), type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
