"""empty message

Revision ID: 7b9dec454e27
Revises: 93e9cbb52829
Create Date: 2026-05-12 04:27:36.280822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9dec454e27'
down_revision = '93e9cbb52829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_shopping_lists')
    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=False))

    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_checked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_creator_id_users'), 'users', ['creator_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_completed_by_id_users'), 'users', ['completed_by_id'], ['id'])
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_completed_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_creator_id_users'), type_='foreignkey')
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('completed_by_id')
        batch_op.drop_column('is_checked')
        batch_op.drop_column('notes')
        batch_op.drop_column('unit')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.drop_column('color')

    op.create_table('_alembic_tmp_shopping_lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('household_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('all_members', sa.BOOLEAN(), nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=False),
    sa.Column('archived_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], name=op.f('fk_shopping_lists_archived_by_users')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_shopping_lists_creator_id_users')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_shopping_lists_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_lists'))
    )
    # ### end Alembic commands ###
