"""empty message

Revision ID: 7c157cb7a5cd
Revises: 9226af4e13e4
Create Date: 2026-07-26 08:58:12.611193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c157cb7a5cd'
down_revision = '9226af4e13e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column( sa.Column('visibility', sa.String(length=10), nullable=False, server_default='public'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
