"""empty message

Revision ID: 7c87f9039c34
Revises: 51ec010d710b
Create Date: 2026-01-15 00:53:05.890003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c87f9039c34'
down_revision = '51ec010d710b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('view_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_sort_order', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('default_filters', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('new_item_position', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('auto_hide_when_empty', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.drop_column('auto_hide_when_empty')
        batch_op.drop_column('new_item_position')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('default_filters')
        batch_op.drop_column('default_sort_order')
        batch_op.drop_column('view_mode')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
