"""empty message

Revision ID: 7cae61c50ac1
Revises: 66c3146d8350
Create Date: 2026-04-13 19:44:30.491415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cae61c50ac1'
down_revision = '66c3146d8350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_note_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_note_categories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_note_categories'))
    )
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_personal_notes_category_id_personal_note_categories'), 'personal_note_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_personal_notes_category_id_personal_note_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('personal_note_categories')
    # ### end Alembic commands ###
