"""empty message

Revision ID: 7d53809109ae
Revises: a93b3b72331d
Create Date: 2026-07-13 19:19:45.950922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d53809109ae'
down_revision = 'a93b3b72331d'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("featured_shopping_list_settings") as batch_op:
        batch_op.add_column(
            sa.Column("view", sa.String(20), nullable=False, server_default="list")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_shopping_list_settings', schema=None) as batch_op:
        batch_op.drop_column('view')

    # ### end Alembic commands ###
