"""shopping lists fresh

Revision ID: 85ca0ce638f0
Revises: 7b9dec454e27
Create Date: 2026-05-12 04:29:10.170845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ca0ce638f0'
down_revision = '7b9dec454e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_shopping_items')
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_checked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_completed_by_id_users'), 'users', ['completed_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_creator_id_users'), 'users', ['creator_id'], ['id'])
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_creator_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_completed_by_id_users'), type_='foreignkey')
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('completed_by_id')
        batch_op.drop_column('is_checked')
        batch_op.drop_column('notes')
        batch_op.drop_column('unit')
        batch_op.drop_column('creator_id')

    op.create_table('_alembic_tmp_shopping_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('list_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_checked', sa.BOOLEAN(), nullable=True),
    sa.Column('completed_by_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shopping_categories.id'], name=op.f('fk_shopping_items_category_id_shopping_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], name=op.f('fk_shopping_items_completed_by_id_users')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_shopping_items_creator_id_users')),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], name=op.f('fk_shopping_items_list_id_shopping_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_items'))
    )
    # ### end Alembic commands ###
