"""empty message

Revision ID: 86785402411f
Revises: f5b9cb6394df
Create Date: 2026-04-07 09:53:57.426128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86785402411f'
down_revision = 'f5b9cb6394df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_households_creator_id_users'), type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_households_creator_id_users'), 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###
