"""empty message

Revision ID: 9226af4e13e4
Revises: c22841eca233
Create Date: 2026-07-18 12:12:31.205538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9226af4e13e4'
down_revision = 'c22841eca233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accent_color', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_column('accent_color')

    # ### end Alembic commands ###
