"""empty message

Revision ID: 948348ea7cf0
Revises: fa3b89cbd975
Create Date: 2026-01-30 07:48:00.301333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948348ea7cf0'
down_revision = 'fa3b89cbd975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasklists_archived_by_users'), 'users', ['archived_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasklists_archived_by_users'), type_='foreignkey')
        batch_op.drop_column('archived_by')

    # ### end Alembic commands ###
