"""empty message

Revision ID: 9d52ed52968e
Revises: 7cae61c50ac1
Create Date: 2026-04-14 09:36:40.270085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d52ed52968e'
down_revision = '7cae61c50ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
