"""empty message

Revision ID: a8c1643d28ab
Revises: b737f786cb44
Create Date: 2026-07-29 17:08:14.059351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c1643d28ab'
down_revision = 'b737f786cb44'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'events_privacy_mode',
            sa.Enum('NORMAL', 'ALL_PRIVATE', 'PRIVATE_BY_DEFAULT', name='privacymode'),
            nullable=False,
            server_default='NORMAL',
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('events_privacy_mode')

    # ### end Alembic commands ###
