"""empty message

Revision ID: a93b3b72331d
Revises: a7ed3f508338
Create Date: 2026-07-03 14:07:43.195645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93b3b72331d'
down_revision = 'a7ed3f508338'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('featured_shopping_list_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('max_items', sa.Integer(), nullable=False),
    sa.Column('show_completed', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Enum('ALPHA', 'CREATED', name='featuredlistsortorder'), nullable=False),
    sa.Column('category_groups', sa.Boolean(), nullable=False),
    sa.Column('show_progress', sa.Boolean(), nullable=True),
    sa.Column('show_quick_add', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], name=op.f('fk_featured_shopping_list_settings_list_id_shopping_lists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_featured_shopping_list_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_featured_shopping_list_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_featured_shopping_list_settings_user_id'))
    )
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    op.drop_table('featured_shopping_list_settings')
    # ### end Alembic commands ###
