"""empty message

Revision ID: acee2f6b19a9
Revises: cc6f52418591
Create Date: 2025-10-03 19:55:37.583427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acee2f6b19a9'
down_revision = 'cc6f52418591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_shopping_categories_list_id_shopping_lists'), 'shopping_lists', ['list_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shopping_categories_list_id_shopping_lists'), type_='foreignkey')
        batch_op.drop_column('list_id')

    # ### end Alembic commands ###
