"""empty message

Revision ID: af533ad7ccb1
Revises: 948348ea7cf0
Create Date: 2026-01-30 12:56:59.216849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af533ad7ccb1'
down_revision = '948348ea7cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.alter_column('default_sort_order',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.alter_column('default_sort_order',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
