"""empty message

Revision ID: afbadfbe5e71
Revises: d3eb45b15f46
Create Date: 2026-05-05 06:23:38.974047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbadfbe5e71'
down_revision = 'd3eb45b15f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_stats', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('featured_stats')

    # ### end Alembic commands ###
