"""empty message

Revision ID: b135ec07548d
Revises: b660944c6def
Create Date: 2026-02-19 22:24:41.219235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b135ec07548d'
down_revision = 'b660944c6def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.alter_column('reminder_type',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.Enum('CUSTOM', 'TASK_DUE', 'EVENT_STARTING', 'DAILY_CHECKIN_MISSING', name='remindertype'),
               existing_nullable=False)
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('featured_tasklist_rotation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_tasklist_rotation', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        batch_op.alter_column('reminder_type',
               existing_type=sa.Enum('CUSTOM', 'TASK_DUE', 'EVENT_STARTING', 'DAILY_CHECKIN_MISSING', name='remindertype'),
               type_=sa.VARCHAR(length=22),
               existing_nullable=False)
        batch_op.drop_column('message')

    # ### end Alembic commands ###
