"""empty message

Revision ID: b2cb54da54c5
Revises: b716e76a9311
Create Date: 2025-12-06 07:09:42.273442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cb54da54c5'
down_revision = 'b716e76a9311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_seen', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcement_seen_announcement_id_announcements'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcement_seen_announcement_id_announcements'), 'announcements', ['announcement_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_column('announcements_ttl_hours')
        batch_op.drop_column('announcements_ttl_mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcements_ttl_mode', sa.VARCHAR(length=8), server_default=sa.text("'rolling'"), nullable=False))
        batch_op.add_column(sa.Column('announcements_ttl_hours', sa.INTEGER(), server_default=sa.text("'24'"), nullable=False))

    with op.batch_alter_table('announcement_seen', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcement_seen_announcement_id_announcements'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcement_seen_announcement_id_announcements'), 'announcements', ['announcement_id'], ['id'])

    # ### end Alembic commands ###
