"""empty message

Revision ID: b660944c6def
Revises: 6ac62bdb6625
Create Date: 2026-02-19 04:41:12.721239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b660944c6def'
down_revision = '6ac62bdb6625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('featured_tasklist_new_task_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_tasklist_new_task_position', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
