"""empty message

Revision ID: b716e76a9311
Revises: 10ef24070015
Create Date: 2025-12-06 06:00:02.597311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b716e76a9311'
down_revision = '10ef24070015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_seen', schema=None) as batch_op:
        batch_op.alter_column('seen_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_announcement_seen_announcement_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_seen_user_id'))
        batch_op.drop_constraint(batch_op.f('uq_seen_announcement_user'), type_='unique')
        batch_op.create_unique_constraint('uq_announcement_user_seen', ['announcement_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('fk_announcement_seen_announcement_id_announcements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_announcement_seen_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcement_seen_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_announcement_seen_announcement_id_announcements'), 'announcements', ['announcement_id'], ['id'])

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_important', sa.Boolean(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_announcements_active'))
        batch_op.drop_index(batch_op.f('ix_announcements_author_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_household_id'))
        batch_op.drop_constraint(batch_op.f('fk_announcements_author_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_announcements_pinned_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcements_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('expires_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('pinned_by')
        batch_op.drop_column('body')
        batch_op.drop_column('pinned_at')
        batch_op.drop_column('author_id')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('archived_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pinned_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('pinned_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_announcements_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcements_pinned_by_users'), 'users', ['pinned_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_announcements_author_id_users'), 'users', ['author_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_announcements_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_active'), ['household_id', 'pinned', 'archived_at', 'expires_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('is_important')
        batch_op.drop_column('message')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('announcement_seen', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcement_seen_announcement_id_announcements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_announcement_seen_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcement_seen_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_announcement_seen_announcement_id_announcements'), 'announcements', ['announcement_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_announcement_user_seen', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_seen_announcement_user'), ['announcement_id', 'user_id'])
        batch_op.create_index(batch_op.f('ix_announcement_seen_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_seen_announcement_id'), ['announcement_id'], unique=False)
        batch_op.alter_column('seen_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
