"""empty message

Revision ID: be533a82f4d5
Revises: 5cd523364f56
Create Date: 2025-10-02 10:57:59.668002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be533a82f4d5'
down_revision = '5cd523364f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Enum('happy', 'content', 'neutral', 'tired', 'stressed', 'sick', 'busy', 'bored', 'accomplished', 'proud', 'excited', 'productive', 'overwhelmed', 'motivated', 'cozy', 'inspired', name='mood_enum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_moods_user_id')
    )
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moods_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moods_user_id'))

    op.drop_table('moods')
    # ### end Alembic commands ###
