"""empty message

Revision ID: c22841eca233
Revises: e53fbb7ee52a
Create Date: 2026-07-18 08:27:43.755077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22841eca233'
down_revision = 'e53fbb7ee52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_household_id_color'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_household_id_color'), ['household_id', 'color'])

    # ### end Alembic commands ###
