"""empty message

Revision ID: c66bc438024e
Revises: 1211806a65ac
Create Date: 2026-03-03 12:49:29.114310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66bc438024e'
down_revision = '1211806a65ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='repeatfrequency'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_column('repeat_frequency')

    # ### end Alembic commands ###
