"""empty message

Revision ID: c8c378fb62f0
Revises: 2cda1106d7b7
Create Date: 2026-09-07 10:25:10.432904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c378fb62f0'
down_revision = '2cda1106d7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exdate', sa.Text(), nullable=True))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('events_color')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_household_color', ['household_id', 'color'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_household_color', type_='unique')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_color', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('exdate')

    # ### end Alembic commands ###
