"""empty message

Revision ID: d3675a50b3ae
Revises: b352aac15b37
Create Date: 2026-02-05 22:40:14.433045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3675a50b3ae'
down_revision = 'b352aac15b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_assignments',
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], name=op.f('fk_reminder_assignments_reminder_id_reminders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminder_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id', 'user_id', name=op.f('pk_reminder_assignments'))
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_assigned_to_id'))
        batch_op.drop_constraint(batch_op.f('fk_reminders_assigned_to_id_users'), type_='foreignkey')
        batch_op.drop_column('seen')
        batch_op.drop_column('assigned_to_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('seen', sa.BOOLEAN(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_reminders_assigned_to_id_users'), 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_reminders_assigned_to_id'), ['assigned_to_id'], unique=False)

    op.drop_table('reminder_assignments')
    # ### end Alembic commands ###
