"""add title not null and is_favorite to personal_notes

Revision ID: d3eb45b15f46
Revises: 9d52ed52968e
Create Date: 2026-04-18 15:27:41.299790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3eb45b15f46'
down_revision = '9d52ed52968e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_personal_notes')
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('is_favorite')

    op.create_table('_alembic_tmp_personal_notes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_private', sa.BOOLEAN(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['personal_note_categories.id'], name=op.f('fk_personal_notes_category_id_personal_note_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_notes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_notes'))
    )
    # ### end Alembic commands ###
