"""empty message

Revision ID: d8616ecc74b7
Revises: bc3f4aee0a2a
Create Date: 2026-04-12 15:24:32.333874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8616ecc74b7'
down_revision = 'bc3f4aee0a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_notes', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
