"""empty message

Revision ID: e4c9b4eb9f15
Revises: 35ec8bf714bb
Create Date: 2025-10-16 01:01:03.491126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c9b4eb9f15'
down_revision = '35ec8bf714bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_seen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('fk_announcement_seen_announcement_id_announcements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_announcement_seen_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement_seen')),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_seen_announcement_user')
    )
    with op.batch_alter_table('announcement_seen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_seen_announcement_id'), ['announcement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_seen_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('pinned_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('ix_announcements_active', ['household_id', 'pinned', 'archived_at', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_household_id'), ['household_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_announcements_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcements_pinned_by_users'), 'users', ['pinned_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_announcements_author_id_users'), 'users', ['author_id'], ['id'])
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('text')
        batch_op.drop_column('user_id')
        batch_op.drop_column('published_at')

    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_shopping_items_shopping_category_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_items_shopping_list_id'))
        batch_op.create_index(batch_op.f('ix_shopping_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_items_list_id'), ['list_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_shopping_category_id_shopping_categories'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_shopping_list_id_shopping_lists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_category_id_shopping_categories'), 'shopping_categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_list_id_shopping_lists'), 'shopping_lists', ['list_id'], ['id'])
        batch_op.drop_column('shopping_category_id')
        batch_op.drop_column('shopping_list_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopping_list_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('shopping_category_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_list_id_shopping_lists'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_category_id_shopping_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_shopping_list_id_shopping_lists'), 'shopping_lists', ['shopping_list_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_shopping_category_id_shopping_categories'), 'shopping_categories', ['shopping_category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_shopping_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_items_category_id'))
        batch_op.create_index(batch_op.f('ix_shopping_items_shopping_list_id'), ['shopping_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_items_shopping_category_id'), ['shopping_category_id'], unique=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('list_id')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_pinned', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_announcements_author_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_announcements_pinned_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcements_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_announcements_household_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_author_id'))
        batch_op.drop_index('ix_announcements_active')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('archived_at')
        batch_op.drop_column('pinned_by')
        batch_op.drop_column('pinned_at')
        batch_op.drop_column('pinned')
        batch_op.drop_column('body')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('announcement_seen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_seen_user_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_seen_announcement_id'))

    op.drop_table('announcement_seen')
    # ### end Alembic commands ###
