"""empty message

Revision ID: e53fbb7ee52a
Revises: f7c2134dfe9c
Create Date: 2026-07-18 08:22:59.791382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e53fbb7ee52a'
down_revision = 'f7c2134dfe9c'
branch_labels = None
depends_on = None


def upgrade():
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_color', sa.VARCHAR(length=20), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_household_id_events_color'), ['household_id', 'events_color'])
        batch_op.drop_column('color')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('google_id', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tagline', sa.VARCHAR(length=100), nullable=True),
    sa.Column('profile_img', sa.VARCHAR(length=256), nullable=True),
    sa.Column('banner_img', sa.VARCHAR(length=256), nullable=True),
    sa.Column('timezone', sa.VARCHAR(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('daily_checkin', sa.BOOLEAN(), nullable=False),
    sa.Column('last_checkin', sa.DATETIME(), nullable=True),
    sa.Column('household_id', sa.INTEGER(), nullable=True),
    sa.Column('removed_from_household_id', sa.INTEGER(), nullable=True),
    sa.Column('featured_stats', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_users_household_id_households')),
    sa.ForeignKeyConstraint(['removed_from_household_id'], ['households.id'], name=op.f('fk_users_removed_from_household_id_households')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id'))
    )
    # ### end Alembic commands ###
