"""empty message

Revision ID: f5b9cb6394df
Revises: efe940dc893f
Create Date: 2026-04-07 09:51:34.152541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b9cb6394df'
down_revision = 'efe940dc893f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_households_admin_id_users'), 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('removed_from_household_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_removed_from_household_id_households'), 'households', ['removed_from_household_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_removed_from_household_id_households'), type_='foreignkey')
        batch_op.drop_column('removed_from_household_id')

    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_households_admin_id_users'), type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
