"""empty message

Revision ID: f65feee1907a
Revises: 016e8b39e666
Create Date: 2026-02-17 05:01:45.564861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65feee1907a'
down_revision = '016e8b39e666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_tasklist_filter_just_me', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured_tasklist_filter_overdue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured_tasklist_filter_due_today', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured_tasklist_filter_due_soon', sa.Boolean(), nullable=True))
        batch_op.drop_column('featured_tasklist_assignee_filter')
        batch_op.drop_column('featured_tasklist_urgency_filter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_tasklist_urgency_filter', sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(sa.Column('featured_tasklist_assignee_filter', sa.VARCHAR(length=9), nullable=False))
        batch_op.drop_column('featured_tasklist_filter_due_soon')
        batch_op.drop_column('featured_tasklist_filter_due_today')
        batch_op.drop_column('featured_tasklist_filter_overdue')
        batch_op.drop_column('featured_tasklist_filter_just_me')

    # ### end Alembic commands ###
