"""empty message

Revision ID: fa3b89cbd975
Revises: 0670a509ba1d
Create Date: 2026-01-24 11:45:39.438846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3b89cbd975'
down_revision = '0670a509ba1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.drop_column('stars_at_top')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_tasklist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_featured_tasklist_id_tasklists'), 'tasklists', ['featured_tasklist_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_featured_tasklist_id_tasklists'), type_='foreignkey')
        batch_op.drop_column('featured_tasklist_id')

    with op.batch_alter_table('tasklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars_at_top', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
