"""empty message

Revision ID: ff82e98db216
Revises: 789a2ceee3ca
Create Date: 2026-05-16 21:56:45.550770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff82e98db216'
down_revision = '789a2ceee3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=30), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
