from sqlalchemy import func, Index, UniqueConstraint
from app.extensions import db
from datetime import datetime, timezone
from enum import Enum
from app.utils.timezone import utc_datetime_to_local

# Reminder model captures both user-created and system-generated reminders for various household-related events (e.g. task due, event starting, daily check-in missed, etc.) - helps with consistent reminder management and potential future analytics on reminder types and effectiveness
class ReminderType(Enum):
    CUSTOM = "custom"
    TASK_DUE = "task_due"
    EVENT_STARTING = "event_starting"
    DAILY_CHECKIN_MISSING = "daily_checkin_missing"

class Reminder(db.Model):
    __tablename__ = "reminders"

    id = db.Column(db.Integer, primary_key=True)

    # Foreign keys
    household_id = db.Column(db.Integer, db.ForeignKey("households.id", ondelete="CASCADE"), nullable=False, index=True) # Each reminder belongs to a household
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True) # The user who created the reminder (can be null if created by system automation or if user was deleted)

    message = db.Column(db.Text, nullable=False) # Main content of the reminder (e.g. "Don't forget to take out the trash tonight!", "You have a dinner event scheduled for 7pm", "It looks like you missed your daily check-in today. Please remember to complete it when you can!", etc.)
    reminder_type = db.Column(db.Enum(ReminderType), nullable=False) # Classifies the type of reminder (e.g. "custom", "task_due", "event_starting", "daily_check_in_missing", etc.) - helps with frontend display logic and potential future analytics
    is_automatic = db.Column(db.Boolean, nullable=False, default=False) # Whether this reminder was automatically generated by the system (e.g. for a due task, upcoming event, or missed daily check-in) vs. manually created by a user - helps with frontend display logic and potential future analytics

    # Source entity (if applicable)
    source_entity_id = db.Column(db.Integer, nullable=True) # e.g. task_id, event_id, etc. - helps link back to the original source that triggered this reminder (if any)
    source_entity_type = db.Column(db.String(50), nullable=True) # e.g. "task", "event", "daily_check_in", etc. - helps clarify the type of source entity for this reminder (if any)

    # Creation and update tracking
    created_at = db.Column(db.DateTime(timezone=True), default=datetime.utcnow, nullable=False) # When the reminder was created
    updated_at = db.Column(db.DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False) # When the reminder was last updated (e.g. title/message edited, trigger time changed, etc.)

    # Automatic reminder lifecycle
    trigger_at = db.Column(db.DateTime(timezone=True), nullable=True, index=True) # -> when scheduler fires
    is_active = db.Column(db.Boolean, nullable=False, default=True, index=True) # Whether or not it's currently active; False means it was "Deactivated" (e.g. task details were edited)
    delivered_at = db.Column(db.DateTime(timezone=True), nullable=True, index=True) # When the reminder was actually delivered to users (via scheduler)

    # Relationships
    created_by = db.relationship("User", foreign_keys=[created_by_id]) # The user who created the reminder (can be null if created by system automation or if user was deleted)
    household = db.relationship("Household", back_populates="reminders") # The household this reminder belongs to
    assignments = db.relationship("ReminderAssignment", cascade="all, delete-orphan", backref="reminder") # The users this reminder is assigned to (via ReminderAssignment association table)

    # Index to optimize queries for active reminders that are due to be triggered (e.g. for scheduler)
    __table_args__ = (
        UniqueConstraint(
            "household_id",
            "source_entity_type",
            "source_entity_id",
            "trigger_at",
            "reminder_type",
            name="uq_auto_reminder_instance",
        ),
    )
    
    def to_dict(self):
        return {
            "id": self.id,
            "householdId": self.household_id,
            "createdById": self.created_by_id,
            "message": self.message,
            "reminderType": self.reminder_type.value,  # ✅ Use .value
            "isAutomatic": self.is_automatic,
            "sourceEntityId": self.source_entity_id,
            "sourceEntityType": self.source_entity_type,
            "triggerAt": self.trigger_at.astimezone(timezone.utc).isoformat() if self.trigger_at else None,
            "isActive": self.is_active,
            "deliveredAt": self.delivered_at.isoformat() if self.delivered_at else None,
            "createdAt": self.created_at.isoformat() if self.created_at else None,
            "updatedAt": self.updated_at.isoformat() if self.updated_at else None,
            "createdBy": {
                "id": self.created_by.id,
                "firstName": self.created_by.first_name,
                "profileImg": self.created_by.profile_img,
            } if self.created_by else None,
            "assignedTo": [
                {
                    "id": a.user.id,
                    "firstName": a.user.first_name,
                    "profileImg": a.user.profile_img,
                }
                for a in self.assignments
            ],
        }

    def to_dict_for_user(self, assignment):
        user = assignment.user

        return {
            "id": self.id,
            "householdId": self.household_id,
            "createdById": self.created_by_id,
            "message": self.message,
            "reminderType": self.reminder_type.value,
            "isAutomatic": self.is_automatic,
            "sourceEntityId": self.source_entity_id,
            "sourceEntityType": self.source_entity_type,

            "triggerAt": (
                utc_datetime_to_local(user, self.trigger_at).isoformat()
                if self.trigger_at else None
            ),

            "deliveredAt": (
                utc_datetime_to_local(user, self.delivered_at).isoformat()
                if self.delivered_at else None
            ),

            "createdAt": (
                utc_datetime_to_local(user, self.created_at).isoformat()
                if self.created_at else None
            ),

            "updatedAt": (
                utc_datetime_to_local(user, self.updated_at).isoformat()
                if self.updated_at else None
            ),

            "isActive": self.is_active,

            "createdBy": {
                "id": self.created_by.id,
                "firstName": self.created_by.first_name,
                "profileImg": self.created_by.profile_img,
            } if self.created_by else None,

            "assignedTo": [
                {
                    "id": a.user.id,
                    "firstName": a.user.first_name,
                    "profileImg": a.user.profile_img,
                }
                for a in self.assignments
            ],

            "currentUserAssignment": {
                "seen": assignment.seen
            }
        }
    
    def __repr__(self):
        return f"<Reminder id={self.id} household_id={self.household_id} created_by_id={self.created_by_id}>"

class ReminderAssignment(db.Model):
    __tablename__ = "reminder_assignments"

    reminder_id = db.Column(db.Integer, db.ForeignKey("reminders.id", ondelete="CASCADE"), primary_key=True) # Each reminder can be assigned to multiple users, and each user can have multiple reminders - this association table captures that many-to-many relationship along with assignment-specific details
    user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True) # Each reminder can be assigned to multiple users, and each user can have multiple reminders - this association table captures that many-to-many relationship along with assignment-specific details
    assigned_at = db.Column(db.DateTime(timezone=True), default=datetime.utcnow, nullable=False) # When the reminder was assigned to this user (e.g. when the reminder was created or when a user was added to an existing reminder)
    seen = db.Column(db.Boolean, nullable=False, default=False) # Whether the assigned user has seen this reminder (e.g. has it shown up in their UI yet)

    def to_dict(self):
        return {
            "reminderId": self.reminder_id,
            "userId": self.user_id,
            "seen": self.seen,
            "assignedAt": self.assigned_at.isoformat(),
        }