from sqlalchemy import func, Index, UniqueConstraint
from app.extensions import db
from datetime import datetime, timezone
from enum import Enum
from app.utils.timezone import utc_datetime_to_local

# Reminder model captures both user-created and system-generated reminders for various household-related events (e.g. task due, event starting, daily check-in missed, etc.) - helps with consistent reminder management and potential future analytics on reminder types and effectiveness
class ReminderType(Enum):
    CUSTOM = "custom"
    TASK_DUE = "task_due"
    EVENT_STARTING = "event_starting"
    DAILY_CHECKIN_MISSING = "daily_checkin_missing"

class RepeatFrequency(Enum):
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"

class Reminder(db.Model):
    __tablename__ = "reminders"

    id = db.Column(db.Integer, primary_key=True)

    # Foreign keys
    household_id = db.Column(db.Integer, db.ForeignKey("households.id", ondelete="CASCADE"), nullable=False, index=True) # Each reminder belongs to a household
    created_by_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True) # The user who created the reminder (can be null if created by system automation or if user was deleted)

    repeat_frequency = db.Column(db.Enum(RepeatFrequency, name="repeatfrequency"), nullable=True, default=None)

    message = db.Column(db.Text, nullable=False) # Main content of the reminder (e.g. "Don't forget to take out the trash tonight!", "You have a dinner event scheduled for 7pm", "It looks like you missed your daily check-in today. Please remember to complete it when you can!", etc.)
    reminder_type = db.Column(db.Enum(ReminderType), nullable=False) # Classifies the type of reminder (e.g. "custom", "task_due", "event_starting", "daily_check_in_missing", etc.) - helps with frontend display logic and potential future analytics
    is_automatic = db.Column(db.Boolean, nullable=False, default=False) # Whether this reminder was automatically generated by the system (e.g. for a due task, upcoming event, or missed daily check-in) vs. manually created by a user - helps with frontend display logic and potential future analytics

    # Source entity (if applicable)
    source_entity_id = db.Column(db.Integer, nullable=True) # e.g. task_id, event_id, etc. - helps link back to the original source that triggered this reminder (if any)
    source_entity_type = db.Column(db.String(50), nullable=True) # e.g. "task", "event", "daily_check_in", etc. - helps clarify the type of source entity for this reminder (if any)

    # Creation and update tracking
    created_at = db.Column(db.DateTime(timezone=True), default=datetime.utcnow, nullable=False) # When the reminder was created
    updated_at = db.Column(db.DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False) # When the reminder was last updated (e.g. title/message edited, trigger date changed, etc.)

    # Reminder lifecycle
    trigger_date = db.Column(db.Date, nullable=True, index=True) # The date on which this reminder becomes visible to assigned users (pulled on login/page load)
    is_active = db.Column(db.Boolean, nullable=False, default=True, index=True) # Whether or not it's currently active; False means it was "Deactivated" (e.g. task details were edited)

    # Relationships
    created_by = db.relationship("User", foreign_keys=[created_by_id]) # The user who created the reminder (can be null if created by system automation or if user was deleted)
    household = db.relationship("Household", back_populates="reminders") # The household this reminder belongs to
    assignments = db.relationship("ReminderAssignment", cascade="all, delete-orphan", backref="reminder") # The users this reminder is assigned to (via ReminderAssignment association table)

    __table_args__ = (
        UniqueConstraint(
            "household_id",
            "source_entity_type",
            "source_entity_id",
            "trigger_date",
            "reminder_type",
            name="uq_auto_reminder_instance",
        ),
    )
    
    def to_dict(self):
        return {
            "id": self.id,
            "householdId": self.household_id,
            "createdById": self.created_by_id,
            "message": self.message,
            "reminderType": self.reminder_type.value,
            "isAutomatic": self.is_automatic,
            "repeatFrequency": self.repeat_frequency.value if self.repeat_frequency else None,
            "sourceEntityId": self.source_entity_id,
            "sourceEntityType": self.source_entity_type,
            "triggerDate": self.trigger_date.isoformat() + "Z" if self.trigger_date else None,
            "isActive": self.is_active,
            "createdAt": self.created_at.isoformat() + "Z" if self.created_at else None,
            "updatedAt": self.updated_at.isoformat() + "Z" if self.updated_at else None,
            "createdBy": {
                "id": self.created_by.id,
                "firstName": self.created_by.first_name,
                "profileImg": self.created_by.profile_img,
            } if self.created_by else None,
            "assignedTo": [
                {
                    "id": a.user.id,
                    "firstName": a.user.first_name,
                    "profileImg": a.user.profile_img,
                }
                for a in self.assignments
            ],
        }

    def to_dict_for_user(self, assignment):
        return {
            "id": self.id,
            "householdId": self.household_id,
            "createdById": self.created_by_id,
            "message": self.message,
            "reminderType": self.reminder_type.value,
            "repeatFrequency": self.repeat_frequency.value if self.repeat_frequency else None,
            "isAutomatic": self.is_automatic,
            "sourceEntityId": self.source_entity_id,
            "sourceEntityType": self.source_entity_type,
            "triggerDate": self.trigger_date.isoformat() if self.trigger_date else None,
            "isActive": self.is_active,
            "createdAt": self.created_at.isoformat() + "Z" if self.created_at else None,
            "updatedAt": self.updated_at.isoformat() + "Z" if self.updated_at else None,
            "createdBy": {
                "id": self.created_by.id,
                "firstName": self.created_by.first_name,
                "profileImg": self.created_by.profile_img,
            } if self.created_by else None,
            "assignedTo": [
                {
                    "id": a.user.id,
                    "firstName": a.user.first_name,
                    "profileImg": a.user.profile_img,
                }
                for a in self.assignments
            ],
            "currentUserAssignment": {
                "seen": assignment.seen
            }
        }
    
    def __repr__(self):
        return f"<Reminder id={self.id} household_id={self.household_id} created_by_id={self.created_by_id}>"

class ReminderAssignment(db.Model):
    __tablename__ = "reminder_assignments"

    reminder_id = db.Column(db.Integer, db.ForeignKey("reminders.id", ondelete="CASCADE"), primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)
    assigned_at = db.Column(db.DateTime(timezone=True), default=datetime.utcnow, nullable=False)
    seen = db.Column(db.Boolean, nullable=False, default=False) # Whether the assigned user has seen this reminder

    def to_dict(self):
        return {
            "reminderId": self.reminder_id,
            "userId": self.user_id,
            "seen": self.seen,
            "assignedAt": self.assigned_at.isoformat(),
        }
